consul: boostrap-acls script improvements
- rotate acl_agent_token only if necessary
- rotate out a bootstrapping gossip encryption key

diff --git a/kubernetes/consul/bootstrap-acls b/kubernetes/consul/bootstrap-acls
--- a/kubernetes/consul/bootstrap-acls
+++ b/kubernetes/consul/bootstrap-acls
@@ -40,21 +40,61 @@ else
   bootstrap_token=$CONSUL_BOOTSTRAP_ACL_TOKEN
 fi
 
-AGENT_POLICY=$(python3 -c "import json; policy_doc = open('policies/agent.hcl', 'rU').read().rstrip(); print(json.dumps(policy_doc))")
-response=$(
-  curl --silent --show-error --fail -XPUT \
-  --header "X-Consul-Token: $bootstrap_token" \
-  --data '{"Name": "Agent Token", "Type": "client", "Rules": '"$AGENT_POLICY"'}' \
-  localhost:$port/v1/acl/create
-)
-if [ $? -ne 0 ]; then
-  echo "Creating Initial Agent Token failed, check networking"
-  echo $response
-  exit 1
-fi
-agent_token=$(echo $response | jq -r '.ID')
-echo "Captured Agent Token, applying to initial cluster"
+keyring=$(curl -s --show-error --fail -H"X-Consul-Token: $bootstrap_token" http://127.0.0.1:$port/v1/operator/keyring)
 
+echo $keyring | jq -r '.[].Keys|keys | .[]' | sort | uniq | grep "aaaaaaaaaaaaaaaaaaaaaQ==" > /dev/null 2>&1
+if [ $? -eq 0 ]; then
+  echo "bootstrapping gossip/encryption key found, performing rotation"
+  new_encrypt_key=$(consul keygen)
+  curl -s --show-error --fail \
+    --header "X-Consul-Token: $bootstrap_token" \
+    --request POST \
+    --data '{"Key": "'"$new_encrypt_key"'"}' \
+    http://127.0.0.1:$port/v1/operator/keyring
+  echo "new key submitted to cluster, allowing to settle..."
+  sleep 5
+  curl -s --show-error --fail \
+    --header "X-Consul-Token: $bootstrap_token" \
+    --request PUT \
+    --data '{"Key": "'"$new_encrypt_key"'"}' \
+    http://127.0.0.1:$port/v1/operator/keyring
+  echo "new key promoted to primary, allowing to settle..."
+  sleep 5
+  kubectl patch secret -n vault consul-gossip-key -p '{"data": {"key": "'"$(printf $new_encrypt_key | openssl base64)"'"}}'
+  echo "Stored consul-gossip-key"
+  curl -s --show-error --fail \
+    --header "X-Consul-Token: $bootstrap_token" \
+    --request DELETE \
+    --data '{"Key": "aaaaaaaaaaaaaaaaaaaaaQ=="}' \
+    http://127.0.0.1:$port/v1/operator/keyring
+  echo "bootstrapping gossip key removed!"
+fi
+
+stored_agent_token=$(kubectl -n vault get secret consul-agent-token -o json | jq -r '.data.token' | openssl base64 -d)
+
+if [ "$stored_agent_token" = "null" ]; then
+  echo "No Agent Token found, creating a new one"
+  AGENT_POLICY=$(python3 -c "import json; policy_doc = open('policies/agent.hcl', 'rU').read().rstrip(); print(json.dumps(policy_doc))")
+  response=$(
+    curl --silent --show-error --fail -XPUT \
+    --header "X-Consul-Token: $bootstrap_token" \
+    --data '{"Name": "Agent Token", "Type": "client", "Rules": '"$AGENT_POLICY"'}' \
+    localhost:$port/v1/acl/create
+  )
+  if [ $? -ne 0 ]; then
+    echo "Creating Initial Agent Token failed, check networking"
+    echo $response
+    exit 1
+  fi
+  agent_token=$(echo $response | jq -r '.ID')
+  echo "Captured newly created Agent Token, storing in secret consul-agent-token"
+  kubectl patch secret -n vault consul-agent-token -p '{"data": {"token": "'"$(printf $agent_token | openssl base64)"'"}}'
+  echo "Stored consul-agent-token"
+else
+  agent_token=$stored_agent_token
+fi
+
+echo "Applying Agent Token to initial cluster"
 for i in 0 1 2; do
   kubectl exec -it --tty -n vault consul-$i -- curl \
       --silent --show-error --fail \
